# What are Numpy and Numpy arrays?

Python objects

*  high-level number objects: integers, floating point
*  containers: lists (costless insertion and append), dictionaries (fast lookup)

Numpy provides

*  extension package to Python for multi-dimensional arrays
*  closer to hardware (efficiency)
*  designed for scientific computation (convenience)
*  Also known as array oriented computing


In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [2]:
type(a)

numpy.ndarray

For example, An array containing:
*  values of an experiment/simulation at discrete time steps
*  signal recorded by a measurement device, e.g. sound wave
*  pixels of an image, grey-level or colour
*  3-D data measured at different X-Y-Z positions, e.g. MRI scan
*  ...

Why it is useful: Memory-efficient container that provides fast numerical operations.

In [17]:
L = range(1000)

In [18]:
%timeit [i**2 for i in L]

The slowest run took 4.94 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 364 µs per loop


In [19]:
a = np.arange(1000)

In [20]:
%timeit a**2

The slowest run took 16.22 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.19 µs per loop


In [21]:
np.array?

In [22]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [23]:
import numpy as np

# Array Creation

In [24]:
a = np.array([0, 1, 2, 3])

In [25]:
a.ndim

1

In [26]:
a.shape

(4,)

In [27]:
len(a)

4

In [28]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [29]:
b, b.ndim, b.shape, len(b)

(array([[0, 1, 2],
        [3, 4, 5]]), 2, (2, 3), 2)

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

In [32]:
type(b)

numpy.ndarray

In [34]:
b.dtype

dtype('int64')

In [36]:
from numpy import pi
np.linspace( 0, 2, 1000 )                 # 9 numbers from 0 to 2

array([ 0.        ,  0.002002  ,  0.004004  ,  0.00600601,  0.00800801,
        0.01001001,  0.01201201,  0.01401401,  0.01601602,  0.01801802,
        0.02002002,  0.02202202,  0.02402402,  0.02602603,  0.02802803,
        0.03003003,  0.03203203,  0.03403403,  0.03603604,  0.03803804,
        0.04004004,  0.04204204,  0.04404404,  0.04604605,  0.04804805,
        0.05005005,  0.05205205,  0.05405405,  0.05605606,  0.05805806,
        0.06006006,  0.06206206,  0.06406406,  0.06606607,  0.06806807,
        0.07007007,  0.07207207,  0.07407407,  0.07607608,  0.07807808,
        0.08008008,  0.08208208,  0.08408408,  0.08608609,  0.08808809,
        0.09009009,  0.09209209,  0.09409409,  0.0960961 ,  0.0980981 ,
        0.1001001 ,  0.1021021 ,  0.1041041 ,  0.10610611,  0.10810811,
        0.11011011,  0.11211211,  0.11411411,  0.11611612,  0.11811812,
        0.12012012,  0.12212212,  0.12412412,  0.12612613,  0.12812813,
        0.13013013,  0.13213213,  0.13413413,  0.13613614,  0.13

In [37]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)

In [19]:
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [ ]:
f

In [38]:
print(x)

[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88692191
  4.95038842  5.01385494  5.07732146  5.14078798  5.2

In [39]:
print(f)

[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-01   1.58001396e-01
   9.50560433e-02   3.17279335e-02  -3.17279335e-02  -9.50560433e-02
  -1.58001396e-01  -2.20310533e-01  -2.81732557e-01  -3.42020143e-01
  -4.00930535e-01  -4.58226522e-01

In [60]:
a = np.arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [61]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [62]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [74]:
d = np.arange(10000)
print(d)

[   0    1    2 ..., 9997 9998 9999]


In [75]:
e = d.reshape(100,100)
print(e)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# Basic Operations

Arithmetic operators on arrays apply elementwise. 
A new array is created and filled with the result.

In [26]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [27]:
c = a-b
c

array([20, 29, 38, 47])

In [28]:
b**2

array([0, 1, 4, 9])

In [29]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [30]:
a<35

array([ True,  True, False, False], dtype=bool)

the product operator * operates elementwise in NumPy arrays

In [31]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [32]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [33]:
np.dot(A, B)           # another matrix product

array([[5, 4],
       [3, 4]])

+= and *=, act in place to modify an existing array rather than create a new one.

In [34]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print(a,b, sep='\n')

[[1 1 1]
 [1 1 1]]
[[ 0.94926871  0.53361664  0.90853382]
 [ 0.2774341   0.98807443  0.38918854]]


In [35]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [36]:
b += a
b

array([[ 3.94926871,  3.53361664,  3.90853382],
       [ 3.2774341 ,  3.98807443,  3.38918854]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [37]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name
c = a+b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [38]:
c.dtype.name

'float64'

# References

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html